app/browser/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^annotation/(?P<protein_id>\S+)/$', views.details, name='details'),
    url(r'^tax/(?P<tax>\w*)/sf/(?P<sf>\w*)/$', views.browse, name='browse'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/tax/(?P<tax>\d*)/sf/(?P<sf>\w*)/$', views.profile_result, name='profile_result'),
    url(r'^taxonomy/(?P<tax>\d*)/$', views.taxonomy, name='taxonomy'),
]

app/rabdb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'rabdb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rabifier/', include('rabifier_app.urls', namespace='rabifier')),
    url(r'^browser/', include('browser.urls', namespace='browser')),
]

app/rabifier_app/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.search, name='search'),
    #url(r'^(?P<ticket>[a-z]+)/$', views.result, name='result'),
    #url(r'^search/$', views.search, name='search'),
    url(r'^(?P<ticket>[\w\-]+)/$', views.result, name='result'),
    #url(r'^done/$', views.result, name='result'),
    #url(r'^(?P<ticket>[0-9]+)/$', views.index, name='index'),
]

app/browser/models.py
from django.db import models
from treebeard.mp_tree import MP_Node


class TaxonomyManager(models.Manager):

    def get_by_natural_key(self, taxon):
        return self.get(taxon=taxon)


class Taxonomy(models.Model):
    objects = TaxonomyManager()

    taxon = models.IntegerField(unique=True)
    name = models.CharField(max_length=128, unique=True)
    name_common = models.CharField(max_length=128, blank=True)

    def __unicode__(self):
        return str(self.taxon)


class ProteinManager(models.Manager):

    def get_by_natural_key(self, protein_id):
        return self.get(protein=protein_id)


class Protein(models.Model):
    objects = ProteinManager()

    protein = models.CharField(max_length=64, unique=True)
    transcript = models.CharField(max_length=64, unique=True)
    gene = models.CharField(max_length=64)
    uniprot = models.CharField(max_length=32, blank=True)
    description = models.TextField()
    seq = models.TextField()
    comment = models.TextField(blank=True)

    def __unicode__(self):
        return str(self.protein)


class Annotation(models.Model):
    protein = models.ForeignKey(Protein)
    taxonomy = models.ForeignKey(Taxonomy)

    gprotein = models.CharField(max_length=32)
    log10_evalue_rab = models.FloatField()
    log10_evalue_nonrab = models.FloatField(blank=True, null=True)
    rabf = models.CharField(max_length=256)
    israb = models.BooleanField()
    rab_subfamily = models.CharField(max_length=16)
    rab_subfamily_score = models.FloatField()
    rab_subfamily_top5 = models.CharField(max_length=256)


class NcbiTaxonomy(MP_Node):
    taxon_id = models.IntegerField(unique=True)
    node_rank = models.CharField(max_length=64)
    taxon_name = models.CharField(max_length=128)

    node_order_by = ['taxon_id']

    def __unicode__(self):
        return 'NcbiTaxonomy: {}'.format(self.taxon_id)

app/browser/forms.py
from django import forms


class RabBrowserForm(forms.Form):

    rab_subfamily = forms.ChoiceField(choices=(), label='Rab subfamily', required=False)
    taxon = forms.ChoiceField(choices=(), label='Taxon', required=False)
    species = forms.ChoiceField(choices=(), label='Species', required=False)

    def __init__(self, rab_subfamily_choices, species_choices, taxon_choices, *args, **kwargs):
        super(RabBrowserForm, self).__init__(*args, **kwargs)
        self.fields['rab_subfamily'].choices = rab_subfamily_choices
        self.fields['taxon'].choices = taxon_choices
        self.fields['species'].choices = species_choices

    def clean(self):
        cleaned_data = super(RabBrowserForm, self).clean()
        sf = cleaned_data.get('rab_subfamily')
        tx = cleaned_data.get('taxon')
        sp = cleaned_data.get('species')

        if sp != 'all' and tx != 'all':
            raise forms.ValidationError('Select either species OR taxon')
        elif all(x == 'all' for x in (sf, sp, tx)):
            raise forms.ValidationError('Select either Rab subfamily OR(and) species or taxon.')


class RabProfileForm(forms.Form):
    rab_subfamily = forms.ChoiceField(choices=(), label='Rab subfamily', required=True)
    taxon = forms.ChoiceField(choices=(), label='Taxon', required=True)

    def __init__(self, rab_subfamily_choices, taxon_choices, *args, **kwargs):
        super(RabProfileForm, self).__init__(*args, **kwargs)
        self.fields['rab_subfamily'].choices = rab_subfamily_choices
        self.fields['taxon'].choices = taxon_choices

    def clean(self):
        cleaned_data = super(RabProfileForm, self).clean()
        sf = cleaned_data.get('rab_subfamily')
        tx = cleaned_data.get('taxon')

        if not all([sf, tx]):
            raise forms.ValidationError('Select both Rab subfamily AND taxon.')


class TaxonomyTreeForm(forms.Form):
    taxon = forms.ChoiceField(choices=(), label='Taxon', required=True)

    def __init__(self, taxon_choices, *args, **kwargs):
        super(TaxonomyTreeForm, self).__init__(*args, **kwargs)
        self.fields['taxon'].choices = taxon_choices

app/browser/views.py
import json
import math
import re

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from networkx.readwrite import json_graph

from .models import Annotation, NcbiTaxonomy, Taxonomy
from .forms import RabBrowserForm, RabProfileForm, TaxonomyTreeForm


def natural_sort(l):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [convert(c) for c in re.split('([0-9]+)', key)]
    return sorted(l, key=alphanum_key)


def get_rab_sf():
    return [(x, x[0].upper() + x[1:]) for x in natural_sort(
        [ann['rab_subfamily'] for ann in Annotation.objects.values('rab_subfamily').distinct()])]


def filter_taxa():
    try:
        graph = json_graph.tree_graph(NcbiTaxonomy.dump_bulk(NcbiTaxonomy.objects.get(taxon_id=1))[0])
    except ObjectDoesNotExist:
        return []
    nodes = [graph.node[x]['data'] for x, d in graph.out_degree().items() if d > 0]
    pattern = re.compile('^[A-Z][a-z]+$')
    ranks = {'no rank', 'kingdom', 'phylum', 'order', 'subkingdom'}
    id_name = []
    for x in nodes:
        if x['node_rank'] in ranks and pattern.findall(x['taxon_name']):
            id_name.append((x['taxon_id'], x['taxon_name']))
    return sorted(id_name, key=lambda x: x[1])


def index(request):
    if request.method == 'POST':
        form = RabBrowserForm(data=request.POST,
                              rab_subfamily_choices=[('all', 'All')] + get_rab_sf(),
                              species_choices=[('all', 'All')] +
                                              [(x.taxon, x.name) for x in Taxonomy.objects.all().order_by('name')],
                              taxon_choices=[('all', 'All')] + filter_taxa())
        if form.is_valid():
            sp = form.cleaned_data['species']
            tx = form.cleaned_data['taxon']
            sf = form.cleaned_data['rab_subfamily']
            if sp != 'all':
                taxon = sp
            else:
                taxon = tx
            return HttpResponseRedirect(reverse('browser:browse', kwargs={'tax': taxon, 'sf': sf}))

    else:
        form = RabBrowserForm(rab_subfamily_choices=[('all', 'All')] + get_rab_sf(),
                              species_choices=[('all', 'All')] +
                                              [(x.taxon, x.name) for x in Taxonomy.objects.all().order_by('name')],
                              taxon_choices=[('all', 'All')] + filter_taxa())

    return render(request, 'browser/index.html', {'form': form})


def details(request, **kwargs):
    ann = get_object_or_404(Annotation, protein__protein=kwargs['protein_id'])

    if 'download' in request.GET:
        response = HttpResponse(content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename="{}.fasta"'.format(ann.protein.protein)
        cut_seq = lambda s: '\n'.join(s[i: i+80] for i in range(0, len(s), 80))
        response.write('>{} {} {}\n{}'.format(ann.protein.protein, ann.taxonomy.name.replace(' ', '_'),
                                              ann.rab_subfamily, cut_seq(ann.protein.seq)))
        return response

    # Helper functions for drawing domains
    MAX_IMG_LEN = 300.0
    seq_len = len(ann.protein.seq)
    rescale = lambda x: math.ceil(x * MAX_IMG_LEN / seq_len)
    get_rectangle = lambda x: {'x1': rescale(x[0]), 'width': rescale(x[1] - x[0]), 'range': '{}-{}'.format(*x)}

    data = {
        'species': ann.taxonomy.name,
        'protein': ann.protein.protein,
        'gene': ann.protein.gene,
        'rab_subfamily': '{}{} ({:.2f})'.format(ann.rab_subfamily[0].upper(), ann.rab_subfamily[1:],
                                                 ann.rab_subfamily_score),
        'top_subfamilies': ['{} ({:.2g})'.format(*(float(y) if y[0].isdigit() else y[0].upper() + y[1:] for y in x.split()))
                            for x in ann.rab_subfamily_top5.split('|')][1:],
        'evalue_rab': '0' if ann.log10_evalue_rab < -323 else '{:.1e}'.format(10**ann.log10_evalue_rab),
        'evalue_non_rab': '>1e-10' if ann.log10_evalue_nonrab is None else '0' if ann.log10_evalue_nonrab < -323 else '{:.1e}'.format(10**ann.log10_evalue_nonrab),
        'rabf_text': ', '.join('({}, {}-{}, {})'.format(*x.split()) for x in ann.rabf.split('|')),
        'rabf': [get_rectangle(list(map(int, x.split()[1:3]))) for x in ann.rabf.split('|')],
        'sequence': ann.protein.seq,
        'gprotein': [get_rectangle(list(map(int, gprot.split('-')))) for gprot in ann.gprotein.split()],
        'img_len': MAX_IMG_LEN
    }
    return render(request, 'browser/annotation.html', {'annotation': data})


def browse(request, **kwargs):
    info = {'rab': kwargs['sf']}
    try:
        if kwargs['tax'] == 'all':
            if kwargs['sf'] != 'all':
                annotations = Annotation.objects.all().order_by('taxonomy__name').filter(rab_subfamily=kwargs['sf'])
            else:
                annotations = Annotation.objects.all().order_by('taxonomy__name')
        else:
            annotations = Annotation.objects.filter(taxonomy__taxon=kwargs['tax'])
            if annotations:
                info['taxon_name'] = Taxonomy.objects.get(taxon=kwargs['tax']).name
                if kwargs['sf'] != 'all':
                    annotations = annotations.filter(rab_subfamily=kwargs['sf'])
                annotations = sorted(annotations, key=lambda ann: [int(c) if c.isdigit() else c.lower() for c in
                                                                   re.split('([0-9]+)', ann.rab_subfamily)])
            else:
                graph = json_graph.tree_graph(NcbiTaxonomy.dump_bulk(NcbiTaxonomy.objects.get(taxon_id=kwargs['tax']))[0])
                leaves = [graph.node[x]['data']['taxon_id'] for x, d in graph.out_degree().items() if d == 0]
                info['taxon_name'] = [graph.node[x]['data']['taxon_name'] for x, d, in graph.in_degree().items() if d == 0][0]
                annotations = Annotation.objects.filter(taxonomy__taxon__in=leaves)
                if kwargs['sf'] != 'all':
                    annotations = annotations.filter(rab_subfamily=kwargs['sf'])

    except Annotation.DoesNotExist:
        raise Http404('No annotations')
    except NcbiTaxonomy.DoesNotExist:
        raise Http404('Taxon does not exist.')

    if len(annotations) == 1:
        return HttpResponseRedirect(reverse('browser:details', kwargs={'protein_id': annotations[0].protein.protein}))

    if 'download' in request.GET:
        response = HttpResponse(content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename="{}.fasta"'.format(kwargs['tax'])
        cut_seq = lambda s: '\n'.join(s[i: i+80] for i in range(0, len(s), 80))
        sequences = ('>{} {} {}\n{}'.format(ann.protein.protein, ann.taxonomy.name.replace(' ', '_'),
                                            ann.rab_subfamily, cut_seq(ann.protein.seq)) for ann in annotations)
        response.write('\n'.join(sequences))
        return response

    paginator = Paginator(annotations, 25, orphans=5)
    page = request.GET.get('page')
    try:
        annotations = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        annotations = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        annotations = paginator.page(paginator.num_pages)

    return render(request, 'browser/browser.html', {'annotations': annotations, 'info': info})


def profile(request):
    taxon_choices = [('', '---')] + filter_taxa()
    rab_subfamily_choices = [('', '---')] + get_rab_sf()
    if request.method == 'POST':
        form_profile = RabProfileForm(data=request.POST,
                                      prefix='profile',
                                      rab_subfamily_choices=rab_subfamily_choices,
                                      taxon_choices=taxon_choices)
        form_tree = TaxonomyTreeForm(data=request.POST,
                                     prefix='tree',
                                     taxon_choices=taxon_choices)
        if 'show_profile' in request.POST and form_profile.is_valid():
            tx = form_profile.cleaned_data['taxon']
            sf = form_profile.cleaned_data['rab_subfamily']
            return HttpResponseRedirect(reverse('browser:profile_result', kwargs={'tax': tx, 'sf': sf}))
        elif 'show_tree' in request.POST and form_tree.is_valid():
            tx = form_tree.cleaned_data['taxon']
            return HttpResponseRedirect(reverse('browser:taxonomy', kwargs={'tax': tx}))
    else:
        form_profile = RabProfileForm(rab_subfamily_choices=rab_subfamily_choices,
                                      taxon_choices=taxon_choices,
                                      prefix='profile')
        form_tree = TaxonomyTreeForm(taxon_choices=taxon_choices,
                                     prefix='tree')
    return render(request, 'browser/profile_index.html', {'form': form_profile, 'form_tree': form_tree})


def profile_result(request, **kwargs):
    graph = json_graph.tree_graph(NcbiTaxonomy.dump_bulk(get_object_or_404(NcbiTaxonomy, taxon_id=kwargs['tax']))[0])
    info = {'taxon_name': [graph.node[x]['data']['taxon_name'] for x, d, in graph.in_degree().items() if d == 0][0],
            'sf': kwargs['sf']}
    tax = int(kwargs['tax'])
    root_node = None
    for node, node_data in graph.nodes_iter(data=True):
        if node_data['data']['taxon_id'] == tax:
            root_node = node
            break
    if not root_node:
        raise Http404('Tree root not found')

    if 'json' in request.GET:
        leaves = [graph.node[x]['data']['taxon_id'] for x, d in graph.out_degree().items() if d == 0]

app/browser/templates/browser/annotation.html
{% extends "base.html" %}

{% block title %}RabDB - Protein{% endblock %}

{% block content %}

<h1>Annotation</h1>

{% if annotation %}

<p><a href="?download">Download sequence as FASTA</a></p>

<table class="browser">
    <tr>
        <th>Species</th>
        <td>{{ annotation.species }}</td>
    </tr>
    <tr>
        <th>Protein name</th>
        <td><a href="http://ensemblgenomes.org/id/{{ annotation.protein }}">{{ annotation.protein }}</a></td>
    </tr>
    <tr>
        <th>Gene name</th>
        <td><a href="http://ensemblgenomes.org/id/{{ annotation.gene }}">{{ annotation.gene }}</a></td>
    </tr>
    <tr>
        <th>Rab subfamily (probability)</th>
        <td>
            <ul>
                <li><strong>{{ annotation.rab_subfamily }}</strong></li>
                {% for sf in annotation.top_subfamilies %}
                    <li>{{ sf }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
    <tr>
        <th>G-protein domains</th>
        <td>
            <svg width="{{ annotation.img_len|add:50 }}px" height="24px">
                <line x1="0" y1="12" x2="{{ annotation.img_len }}px" y2="12" style="stroke:black;stroke-width:1" />
                {% for domain in annotation.gprotein %}
                <g>
                    <title>{{ domain.range }} aa</title>
                    <rect x="{{ domain.x1 }}" y="6" width="{{ domain.width }}" height="12" style="fill:#b33c30;stroke:#b33c30;"/>
                </g>
                {% endfor %}
            </svg>
        </td>
    </tr>
    <tr>
        <th>Rab F motifs</th>
        <td>
            <svg width="{{ annotation.img_len|add:50 }}px" height="24px">
                <line x1="0" y1="12" x2="{{ annotation.img_len }}px" y2="12" style="stroke:black;stroke-width:1" />
                {% for domain in annotation.rabf %}
                <g>
                    <title>{{ domain.range }} aa</title>
                <rect x="{{ domain.x1 }}" y="6" width="{{ domain.width }}" height="12" style="fill:grey;stroke:grey;"/>
                </g>
                {% endfor %}
            </svg>
        </td>
    </tr>
    <tr>
        <th>e-value vs. Rab database</th>
        <td>{{ annotation.evalue_rab }}</td>
    </tr>
    <tr>
        <th>e-value vs. non-Rab database</th>
        <td>{{ annotation.evalue_non_rab }}</td>
    </tr>
    <tr>
        <th>Sequence</th>
        <td style="font-family:monospace;word-wrap:break-word;">{{ annotation.sequence }}</td>
    </tr>
</table>
{% else %}
<p>No annotation.</p>
{% endif %}

{% endblock %}

app/browser/templates/browser/browser.html
{% extends "base.html" %}

{% block title %}RabDB - Search | {{ info.taxon_name }}{% endblock %}

{% block content %}

<h1>Rab Search</h1>

<h2>{{ info.taxon_name }}</h2>

{% if annotations %}
    <p><a href="?download">Download sequences as FASTA</a></p>
    <table class="browser">
        <tr>
            <th>Protein</th>
            <th>Species</th>
            <th>Annotation</th>
        </tr>
        {% for annotation in annotations %}
            <tr>
                <td><a href="{% url 'browser:details' annotation.protein.protein %}">{{ annotation.protein.protein }}</a></td>
                <td>{{ annotation.taxonomy.name }}</td>
                <td>{{ annotation.rab_subfamily|capfirst }}</td>
            </tr>
        {% endfor %}
    </table>

<br>

<div id="pagination">
    <ul>
        {% if annotations.has_previous %}
        <li><a href="?page=1">&#10096;&#10096;</a></li>
        <li><a href="?page={{ annotations.previous_page_number }}">&#10096;</a></li>
        {% else %}
        <li class="empty">&#10096;&#10096;</li>
        <li class="empty">&#10096;</li>
        {% endif %}

        <li class="pagination-current">Page {{ annotations.number }} of {{ annotations.paginator.num_pages }}</li>

        {% if annotations.has_next %}
        <li><a href="?page={{ annotations.next_page_number }}">&#10097;</a></li>
        <li><a href="?page={{ annotations.paginator.num_pages }}">&#10097;&#10097;</a></li>
        {% else %}
        <li class="empty">&#10097;</li>
        <li class="empty">&#10097;&#10097;</li>
        {% endif %}
    </ul>
</div>

{% else %}

<p>No {{ info.rab|capfirst }} in {{ info.taxon_name }}</p>

{% endif %}


{% endblock %}

app/browser/templates/browser/index.html
{% extends "base.html" %}

{% block title %}RabDB - Search{% endblock %}

{% block content %}

<h1>Search</h1>

<p>Here you can search for all Rabs identified by the <a href="{% url 'rabifier:search' %}">Rabifier2</a> in 244 genomes
    from <a href="http://www.ensembl.org">Ensembl</a> and <a href="http://ensemblgenomes.org">Ensembl Genomes</a>
    databases.
</p>

<p>Select a Rab subfamily, species, or taxon of interest, and hit 'search' to retrieve all Rabs and their annotation.
You can also search for all Rabs of one subfamily in a single species (e.g. all Rab11 in <em>Homo Sapiens</em>)
or all Rabs of one subfamily in a Taxon (e.g all Rab11 in Metazoa).</p>

<form action="{% url 'browser:index' %}" method="post">
    {% csrf_token %}
    <table class="onlydropdown">{{ form.as_table }}</table>
    <p><input type="submit" value="Search" /></p>
</form>

{% endblock %}

app/browser/templates/browser/profile_index.html
{% extends "base.html" %}

{% block title %}RabDB - Browser{% endblock %}

{% block content %}

<h1>Rab Browser</h1>

<p>Here you can browse all Rabs identified by the Rabifier in 244 genomes included in
    <a href="http://www.ensembl.org">Ensembl</a> and <a href="http://ensemblgenomes.org">Ensembl Genomes</a>
    databases.</p>

<p>Select a Rab subfamily and taxon of interest, hit 'generate profile' to see the profile of presence and absence
    of selected Rab in the taxonomic context.</p>

<form action="{% url 'browser:profile' %}" method="post">
    {% csrf_token %}
    <table class="onlydropdown">{{ form.as_table }}</table>
    <p><input type="submit" value="Generate profile" name="show_profile" /></p>
</form>

<p style="margin-top:30px;">You can also display a species tree, for a given taxon, to browse all Rabs in the taxonomic context.</p>

<form action="{% url 'browser:profile' %}" method="post">
    {% csrf_token %}
    <table class="onlydropdown">{{ form_tree.as_table }}</table>
    <p><input type="submit" value="Show tree" name="show_tree" /></p>
</form>

<p style="margin-top:30px;">If you wish to browse Rabs in any other way please contact us.</p>

{% endblock %}

app/browser/templates/browser/profile_result.html
{% extends "base.html" %}

{% block title %}RabDB - Profile | {{ info.sf|capfirst }} in {{ info.taxon_name }}{% endblock %}

{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'browser/dendrogram.css' %}" />
{% endblock %}

{% block content %}

<h1>Rab Profiles</h1>

<h2>{{ info.sf }} in {{ info.taxon_name }}</h2>

<p>This is a profile of {{ info.sf|capfirst }} in {{ info.taxon_name }}.
    A <span style="color:#33ad33;">green dot</span> indicates that the species has at least one {{ info.sf|capfirst }}.
    The tree is an approximate evolutionary tree based on
    <a href="http://www.ncbi.nlm.nih.gov/taxonomy">NCBI taxonomy</a>.</p>

<p style="margin-bottom:30px;">Hover over any node to see the taxon name, click on any taxon to see all
    {{ info.sf|capfirst }} in that taxon.</p>

<script src="http://d3js.org/d3.v4.min.js"></script>
<script src="{% static 'browser/dendrogram.js' %}"></script>
<script>
  plotTaxonomy('#content', function() {
    d3.selectAll('circle')
      .attr("class", function(d) {
        if (d.children) {return "internal"; }
        else if (d.data.has_rab) { return "positive"; }
        else { return "negative"; }
    });
  });
</script>

{% endblock %}

app/browser/templates/browser/taxonomy.html
{% extends "base.html" %}

{% block title %}RabDB - Taxonomy | {{ info.taxon_name }}{% endblock %}

{% load staticfiles %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'browser/dendrogram.css' %}" />
{% endblock %}

{% block content %}

<h1>Taxonomy</h1>

<h2>{{ info.taxon_name }}</h2>

<p style="margin-bottom:30px;">This is an approximate evolutionary tree of {{ info.taxon_name }} based on
    <a href="http://www.ncbi.nlm.nih.gov/taxonomy">NCBI taxonomy</a>. Hover over any node to see the taxon name,
    click on any taxon to see all Rabs in that taxon.</p>

<script src="http://d3js.org/d3.v4.min.js"></script>
<script src="{% static 'browser/dendrogram.js' %}"></script>
<script>
  plotTaxonomy('#content');
</script>

{% endblock %}